"""initial_schema

Revision ID: 43e68b1dc730
Revises: 
Create Date: 2026-09-01 18:26:36.823780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43e68b1dc730'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_nombre'), 'area', ['nombre'], unique=True)
    op.create_table('capa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capa_nombre'), 'capa', ['nombre'], unique=True)
    op.create_table('frecuencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frecuencia_nombre'), 'frecuencia', ['nombre'], unique=True)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('capa_id', sa.Integer(), nullable=False),
    sa.Column('frecuencia_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['capa_id'], ['capa.id'], ),
    sa.ForeignKeyConstraint(['frecuencia_id'], ['frecuencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_nombre'), 'auditoria', ['nombre'], unique=False)
    op.create_table('celula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'numero')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contrasena_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_table('criterio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('auditoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ejecucion_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('auditoria_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('celula_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ),
    sa.ForeignKeyConstraint(['celula_id'], ['celula.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_area',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'area_id')
    )
    op.create_table('respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('ejecucion_auditoria_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterio.id'], ),
    sa.ForeignKeyConstraint(['ejecucion_auditoria_id'], ['ejecucion_auditoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ejecucion_auditoria_id', 'criterio_id', name='uq_respuesta_ejecucion_criterio')
    )
    op.create_table('hallazgo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('respuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['respuesta_id'], ['respuesta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('respuesta_id')
    )
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('tipo_archivo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('hallazgo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['hallazgo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hallazgo_responsable',
    sa.Column('hallazgo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['hallazgo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('hallazgo_id', 'usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hallazgo_responsable')
    op.drop_table('evidencia')
    op.drop_table('hallazgo')
    op.drop_table('respuesta')
    op.drop_table('usuario_area')
    op.drop_table('ejecucion_auditoria')
    op.drop_table('criterio')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('celula')
    op.drop_index(op.f('ix_auditoria_nombre'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_frecuencia_nombre'), table_name='frecuencia')
    op.drop_table('frecuencia')
    op.drop_index(op.f('ix_capa_nombre'), table_name='capa')
    op.drop_table('capa')
    op.drop_index(op.f('ix_area_nombre'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
